{
 "kind": "discovery#restDescription",
 "etag": "\"uUWyYHXmEn-ab7WLvo8qNz2S8ws/sCAxuVQJb4ynjZxsnsm28T2muEw\"",
 "discoveryVersion": "v1",
 "id": "webmasters:v3",
 "name": "webmasters",
 "version": "v3",
 "revision": "20140908",
 "title": "Webmaster Tools API",
 "description": "Lets you view Google Webmaster Tools data for your verified sites.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/webmaster-tools/v3/welcome",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/webmasters/v3/",
 "basePath": "/webmasters/v3/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "webmasters/v3/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/webmasters": {
     "description": "View and modify Webmaster Tools data for your verified sites"
    },
    "https://www.googleapis.com/auth/webmasters.readonly": {
     "description": "View Webmaster Tools data for your verified sites"
    }
   }
  }
 },
 "resources": {
  "sitemaps": {
   "methods": {
    "delete": {
     "id": "webmasters.sitemaps.delete",
     "path": "sites/{siteUrl}/sitemaps/{feedpath}",
     "httpMethod": "DELETE",
     "description": "Deletes a sitemap from this site.",
     "scopes": [
      "https://www.googleapis.com/auth/webmasters"
     ]
    },
    "get": {
     "id": "webmasters.sitemaps.get",
     "path": "sites/{siteUrl}/sitemaps/{feedpath}",
     "httpMethod": "GET",
     "description": "Retrieves information about a specific sitemap.",
     "scopes": [
      "https://www.googleapis.com/auth/webmasters",
      "https://www.googleapis.com/auth/webmasters.readonly"
     ]
    },
    "list": {
     "id": "webmasters.sitemaps.list",
     "path": "sites/{siteUrl}/sitemaps",
     "httpMethod": "GET",
     "description": "Lists sitemaps uploaded to the site.",
     "scopes": [
      "https://www.googleapis.com/auth/webmasters",
      "https://www.googleapis.com/auth/webmasters.readonly"
     ]
    },
    "submit": {
     "id": "webmasters.sitemaps.submit",
     "path": "sites/{siteUrl}/sitemaps/{feedpath}",
     "httpMethod": "PUT",
     "description": "Submits a sitemap for a site.",
     "scopes": [
      "https://www.googleapis.com/auth/webmasters"
     ]
    }
   }
  },
  "sites": {
   "methods": {
    "add": {
     "id": "webmasters.sites.add",
     "path": "sites/{siteUrl}",
     "httpMethod": "PUT",
     "description": "Adds a site to the set of the user's sites in Webmaster Tools.",
     "scopes": [
      "https://www.googleapis.com/auth/webmasters"
     ]
    },
    "delete": {
     "id": "webmasters.sites.delete",
     "path": "sites/{siteUrl}",
     "httpMethod": "DELETE",
     "description": "Removes a site from the set of the user's Webmaster Tools sites.",
     "scopes": [
      "https://www.googleapis.com/auth/webmasters"
     ]
    },
    "get": {
     "id": "webmasters.sites.get",
     "path": "sites/{siteUrl}",
     "httpMethod": "GET",
     "description": "Retrieves information about specific site.",
     "scopes": [
      "https://www.googleapis.com/auth/webmasters",
      "https://www.googleapis.com/auth/webmasters.readonly"
     ]
    },
    "list": {
     "id": "webmasters.sites.list",
     "path": "sites",
     "httpMethod": "GET",
     "description": "Lists your Webmaster Tools sites.",
     "scopes": [
      "https://www.googleapis.com/auth/webmasters",
      "https://www.googleapis.com/auth/webmasters.readonly"
     ]
    }
   }
  },
  "urlcrawlerrorscounts": {
   "methods": {
    "query": {
     "id": "webmasters.urlcrawlerrorscounts.query",
     "path": "sites/{siteUrl}/urlCrawlErrorsCounts/query",
     "httpMethod": "GET",
     "description": "Retrieves a time series of the number of URL crawl errors per error category and platform.",
     "scopes": [
      "https://www.googleapis.com/auth/webmasters",
      "https://www.googleapis.com/auth/webmasters.readonly"
     ]
    }
   }
  },
  "urlcrawlerrorssamples": {
   "methods": {
    "get": {
     "id": "webmasters.urlcrawlerrorssamples.get",
     "path": "sites/{siteUrl}/urlCrawlErrorsSamples/{url}",
     "httpMethod": "GET",
     "description": "Retrieves details about crawl errors for a site's sample URL.",
     "scopes": [
      "https://www.googleapis.com/auth/webmasters",
      "https://www.googleapis.com/auth/webmasters.readonly"
     ]
    },
    "list": {
     "id": "webmasters.urlcrawlerrorssamples.list",
     "path": "sites/{siteUrl}/urlCrawlErrorsSamples",
     "httpMethod": "GET",
     "description": "Lists a site's sample URLs for the specified crawl error category and platform.",
     "scopes": [
      "https://www.googleapis.com/auth/webmasters",
      "https://www.googleapis.com/auth/webmasters.readonly"
     ]
    },
    "markAsFixed": {
     "id": "webmasters.urlcrawlerrorssamples.markAsFixed",
     "path": "sites/{siteUrl}/urlCrawlErrorsSamples/{url}",
     "httpMethod": "DELETE",
     "description": "Marks the provided site's sample URL as fixed, and removes it from the samples list.",
     "scopes": [
      "https://www.googleapis.com/auth/webmasters"
     ]
    }
   }
  }
 }
}
