version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "area/dependencies"
    schedule:
      interval: "daily"
    groups:
      go:
        patterns:
          - "*"
        exclude-patterns:
          - "go.etcd.io/*"
      etcd:
        patterns:
          - "go.etcd.io/*"

  - package-ecosystem: "gomod"
    directory: "/api/v2"
    labels:
      - "area/dependencies"
    schedule:
      interval: "daily"
    groups:
      go:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/examples"
    labels:
      - "area/dependencies"
    schedule:
      interval: "daily"
    groups:
      go:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - "area/dependencies"
    schedule:
      interval: "daily"
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    labels:
      - "area/dependencies"
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"
