run:
    timeout: 4m
    skip-dirs:
        - storage/ent/db # generated ent code

linters-settings:
    depguard:
      rules:
        deprecated:
          deny:
            - pkg: "io/ioutil"
              desc: "The 'io/ioutil' package is deprecated. Use corresponding 'os' or 'io' functions instead."
    gci:
        local-prefixes: github.com/dexidp/dex
    goimports:
        local-prefixes: github.com/dexidp/dex


linters:
    disable-all: true
    enable:
        - depguard
        - dogsled
        - exhaustive
        - exportloopref
        - gci
        - gochecknoinits
        - gocritic
        - gofmt
        - gofumpt
        - goimports
        - goprintffuncname
        - gosimple
        - govet
        - ineffassign
        - misspell
        - nakedret
        - nolintlint
        - prealloc
        # - revive
        # - sqlclosecheck
        - staticcheck
        - stylecheck
        - unconvert
        - unused
        - whitespace

        # Disable temporarily until everything works with Go 1.20
        # - bodyclose
        # - rowserrcheck
        # - tparallel
        # - unparam

        # Disable temporarily until everything works with Go 1.18
        - typecheck

        # Disable temporarily until the following issue is resolved: https://github.com/golangci/golangci-lint/issues/3086
        # - sqlclosecheck

        # TODO: fix linter errors before enabling
        # - exhaustivestruct
        # - gochecknoglobals
        # - errorlint
        # - gocognit
        # - godot
        # - nlreturn
        # - noctx
        # - revive
        # - wrapcheck

        # TODO: fix linter errors before enabling (from original config)
        # - dupl
        # - errcheck
        # - goconst
        # - gocyclo
        # - gosec
        # - lll
        # - scopelint

        # unused
        # - goheader
        # - gomodguard

        # don't enable:
        # - asciicheck
        # - funlen
        # - godox
        # - goerr113
        # - gomnd
        # - interfacer
        # - maligned
        # - nestif
        # - testpackage
        # - wsl
