#!/bin/bash -e
#
# Build dex for Linux using Docker.

buildImage="dex-builder:$( ./git-version )"
tempdir="$( mktemp -d )"
cidfile="${tempdir}/cid"

cleanup() {
    echo "Cleaning up"
    docker rm $( cat $cidfile )
    rm -rf $tempdir
    docker rmi $buildImage
}
trap cleanup EXIT

echo "Creating build image"

docker build -t $buildImage -f Dockerfile-builder .

echo "Building binaries"

docker run --cidfile=${cidfile} $buildImage ./build
cid=$( cat ${cidfile} )

buildpath=/dex/gopath/src/github.com/coreos/dex/bin

echo "Copying binaries from image"

rm bin/*
docker cp ${cid}:${buildpath}/dex-worker bin/dex-worker
docker cp ${cid}:${buildpath}/dex-overlord bin/dex-overlord
docker cp ${cid}:${buildpath}/dexctl bin/dexctl
