#!/bin/bash -e

mkdir -p deploy

required=(
  ${DEX_OVERLORD_DB_URL:?"missing"}
  ${DEX_OVERLORD_KEY_SECRET:?"missing"}
  ${DEX_WORKER_DB_URL:?"missing"}
  ${DEX_WORKER_KEY_SECRET:?"missing"}
)

eval "cat <<EOF
$(<static/dex-worker.service.tmpl)
EOF
" 1> deploy/dex-worker.service

eval "cat <<EOF
$(<static/dex-overlord.service.tmpl)
EOF
" 1> deploy/dex-overlord.service
