FROM alpine:3.4

MAINTAINER Stijn De Haes <stijndehaes@gmail.com>

# Dex connectors, such as GitHub and Google logins require root certificates.
# Proper installations should manage those certificates, but it's a bad user
# experience when this doesn't work out of the box.
#
# OpenSSL is required so wget can query HTTPS endpoints for health checking.
RUN apk add --update ca-certificates openssl

COPY _output/bin/example-app /usr/local/bin/example-app

WORKDIR /

ENTRYPOINT ["example-app"]

EXPOSE 5555

CMD ["version"]
