{
 "kind": "discovery#restDescription",
 "etag": "\"l66ggWbucbkBw9Lpos72oziyefE/MkEFbbfro6Rau0xbZXwz9DhAfqM\"",
 "discoveryVersion": "v1",
 "id": "replicapoolupdater:v1beta1",
 "name": "replicapoolupdater",
 "version": "v1beta1",
 "revision": "20141105",
 "title": "Google Compute Engine Instance Group Updater API",
 "description": "The Google Compute Engine Instance Group Updater API provides services for updating groups of Compute Engine Instances.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/compute/docs/instance-groups/manager/v1beta2",
 "labels": [
  "limited_availability"
 ],
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/replicapoolupdater/v1beta1/projects/",
 "basePath": "/replicapoolupdater/v1beta1/projects/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "replicapoolupdater/v1beta1/projects/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/cloud-platform": {
     "description": "View and manage your data across Google Cloud Platform services"
    },
    "https://www.googleapis.com/auth/replicapool": {
     "description": "View and manage replica pools"
    },
    "https://www.googleapis.com/auth/replicapool.readonly": {
     "description": "View replica pools"
    }
   }
  }
 },
 "resources": {
  "updates": {
   "methods": {
    "cancel": {
     "id": "replicapoolupdater.updates.cancel",
     "path": "{project}/zones/{zone}/instanceGroupManagers/{instanceGroupManager}/updates/{update}/cancel",
     "httpMethod": "POST",
     "description": "Called on the particular Update endpoint. Cancels the update in state PAUSED. No-op if invoked in state CANCELLED.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    },
    "get": {
     "id": "replicapoolupdater.updates.get",
     "path": "{project}/zones/{zone}/instanceGroupManagers/{instanceGroupManager}/updates/{update}",
     "httpMethod": "GET",
     "description": "Called on the particular Update endpoint. Returns the Update resource.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool",
      "https://www.googleapis.com/auth/replicapool.readonly"
     ]
    },
    "insert": {
     "id": "replicapoolupdater.updates.insert",
     "path": "{project}/zones/{zone}/instanceGroupManagers/{instanceGroupManager}/updates",
     "httpMethod": "POST",
     "description": "Called on the collection endpoint. Inserts the new Update resource and starts the update.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    },
    "list": {
     "id": "replicapoolupdater.updates.list",
     "path": "{project}/zones/{zone}/instanceGroupManagers/{instanceGroupManager}/updates",
     "httpMethod": "GET",
     "description": "Called on the collection endpoint. Lists updates for a given instance group, in reverse chronological order. Pagination is supported, see ListRequestHeader.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool",
      "https://www.googleapis.com/auth/replicapool.readonly"
     ]
    },
    "pause": {
     "id": "replicapoolupdater.updates.pause",
     "path": "{project}/zones/{zone}/instanceGroupManagers/{instanceGroupManager}/updates/{update}/pause",
     "httpMethod": "POST",
     "description": "Called on the particular Update endpoint. Pauses the update in state from { ROLLING_FORWARD, ROLLING_BACK, PAUSED }. No-op if invoked in state PAUSED.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    },
    "rollback": {
     "id": "replicapoolupdater.updates.rollback",
     "path": "{project}/zones/{zone}/instanceGroupManagers/{instanceGroupManager}/updates/{update}/rollback",
     "httpMethod": "POST",
     "description": "Called on the particular Update endpoint. Rolls back the update in state from { ROLLING_FORWARD, ROLLING_BACK, PAUSED }. No-op if invoked in state ROLLED_BACK.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    },
    "rollforward": {
     "id": "replicapoolupdater.updates.rollforward",
     "path": "{project}/zones/{zone}/instanceGroupManagers/{instanceGroupManager}/updates/{update}/rollforward",
     "httpMethod": "POST",
     "description": "Called on the particular Update endpoint. Rolls forward the update in state from { ROLLING_FORWARD, ROLLING_BACK, PAUSED }. No-op if invoked in state ROLLED_OUT.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    }
   }
  }
 }
}
