// Package ldap implements strategies for authenticating using the LDAP protocol.
package ldap

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"fmt"
	"log/slog"
	"net"
	"net/url"
	"os"
	"strings"

	"github.com/go-ldap/ldap/v3"

	"github.com/dexidp/dex/connector"
)

// Config holds the configuration parameters for the LDAP connector. The LDAP
// connectors require executing two queries, the first to find the user based on
// the username and password given to the connector. The second to use the user
// entry to search for groups.
//
// An example config:
//
//     type: ldap
//     config:
//       host: ldap.example.com:636
//       # The following field is required if using port 389.
//       # insecureNoSSL: true
//       rootCA: /etc/dex/ldap.ca
//       bindDN: uid=serviceaccount,cn=users,dc=example,dc=com
//       bindPW: password
//       userSearch:
//         # Would translate to the query "(&(objectClass=person)(|(uid=<username>)(mail=<username>)))"
//         baseDN: cn=users,dc=example,dc=com
//         filter: "(objectClass=person)"
//         username:
//         - uid
//         - mail
//         idAttr: uid
//         emailAttr: mail
//         nameAttr: name
//         preferredUsernameAttr: uid
//       groupSearch:
//         # Would translate to the separate query per user matcher pair and aggregate results into a single group list:
//         #  "(&(|(objectClass=posixGroup)(objectClass=groupOfNames))(memberUid=<user uid>))"
//         #  "(&(|(objectClass=posixGroup)(objectClass=groupOfNames))(member=<user DN>))"
//         baseDN: cn=groups,dc=example,dc=com
//         filter: "(|(objectClass=posixGroup)(objectClass=groupOfNames))"
//         userMatchers:
//         - userAttr: uid
//           groupAttr: memberUid
//           # Use if full DN is needed and not available as any other attribute
//           # Will only work if "DN" attribute does not exist in the record:
//         - userAttr: DN
//           groupAttr: member
//         nameAttr: name
//

// UsernameAttributes represents one or more LDAP attributes to match against
// the username input. It supports unmarshaling from both a single string
// (e.g. "uid") and a list of strings (e.g. ["uid", "mail"]).
type UsernameAttributes []string

func (u *UsernameAttributes) UnmarshalJSON(data []byte) error {
	var arr []string
	if err := json.Unmarshal(data, &arr); err == nil {
		*u = arr
		return nil
	}
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("username must be a string or list of strings")
	}
	if s != "" {
		*u = UsernameAttributes{s}
	}
	return nil
}

// UserMatcher holds information about user and group matching.
type UserMatcher struct {
	UserAttr  string `json:"userAttr"`
	GroupAttr string `json:"groupAttr"`
	// Look for parent groups
	RecursionGroupAttr string `json:"recursionGroupAttr"`
}

// Config holds configuration options for LDAP logins.
type Config struct {
	// The host and optional port of the LDAP server. If port isn't supplied, it will be
	// guessed based on the TLS configuration. 389 or 636.
	Host string `json:"host"`

	// Required if LDAP host does not use TLS.
	InsecureNoSSL bool `json:"insecureNoSSL"`

	// Don't verify the CA.
	InsecureSkipVerify bool `json:"insecureSkipVerify"`

	// Connect to the insecure port then issue a StartTLS command to negotiate a
	// secure connection. If unsupplied secure connections will use the LDAPS
	// protocol.
	StartTLS bool `json:"startTLS"`

	// Path to a trusted root certificate file.
	RootCA string `json:"rootCA"`
	// Path to a client cert file generated by rootCA.
	ClientCert string `json:"clientCert"`
	// Path to a client private key file generated by rootCA.
	ClientKey string `json:"clientKey"`
	// Base64 encoded PEM data containing root CAs.
	RootCAData []byte `json:"rootCAData"`

	// BindDN and BindPW for an application service account. The connector uses these
	// credentials to search for users and groups.
	BindDN string `json:"bindDN"`
	BindPW string `json:"bindPW"`

	// UsernamePrompt allows users to override the username attribute (displayed
	// in the username/password prompt). If unset, the handler will use
	// "Username".
	UsernamePrompt string `json:"usernamePrompt"`

	// Optional Kerberos (SPNEGO) SSO configuration.
	Kerberos *kerberosConfig `json:"kerberos"`

	// User entry search configuration.
	UserSearch struct {
		// BaseDN to start the search from. For example "cn=users,dc=example,dc=com"
		BaseDN string `json:"baseDN"`

		// Optional filter to apply when searching the directory. For example "(objectClass=person)"
		Filter string `json:"filter"`

		// Attribute(s) to match against the inputted username. Accepts a single string
		// or a list of strings. When multiple attributes are specified, an OR filter is
		// constructed: "(|(<attr1>=<username>)(<attr2>=<username>))".
		Username UsernameAttributes `json:"username"`

		// Can either be:
		// * "sub" - search the whole sub tree
		// * "one" - only search one level
		Scope string `json:"scope"`

		// A mapping of attributes on the user entry to claims.
		IDAttr                    string `json:"idAttr"`                // Defaults to "uid"
		EmailAttr                 string `json:"emailAttr"`             // Defaults to "mail"
		NameAttr                  string `json:"nameAttr"`              // No default.
		PreferredUsernameAttrAttr string `json:"preferredUsernameAttr"` // No default.

		// If this is set, the email claim of the id token will be constructed from the idAttr and
		// value of emailSuffix. This should not include the @ character.
		EmailSuffix string `json:"emailSuffix"` // No default.
	} `json:"userSearch"`

	// Group search configuration.
	GroupSearch struct {
		// BaseDN to start the search from. For example "cn=groups,dc=example,dc=com"
		BaseDN string `json:"baseDN"`

		// Optional filter to apply when searching the directory. For example "(objectClass=posixGroup)"
		Filter string `json:"filter"`

		Scope string `json:"scope"` // Defaults to "sub"

		// DEPRECATED config options. Those are left for backward compatibility.
		// See "UserMatchers" below for the current group to user matching implementation
		// TODO: should be eventually removed from the code
		UserAttr  string `json:"userAttr"`
		GroupAttr string `json:"groupAttr"`

		RecursionGroupAttr string `json:"recursionGroupAttr"`

		// Array of the field pairs used to match a user to a group.
		// See the "UserMatcher" struct for the exact field names
		//
		// Each pair adds an additional requirement to the filter that an attribute in the group
		// match the user's attribute value. For example that the "members" attribute of
		// a group matches the "uid" of the user. The exact filter being added is:
		//
		//   (userMatchers[n].<groupAttr>=userMatchers[n].<userAttr value>)
		//
		UserMatchers []UserMatcher `json:"userMatchers"`

		// The attribute of the group that represents its name.
		NameAttr string `json:"nameAttr"`
	} `json:"groupSearch"`
}

// kerberosConfig defines optional Kerberos (SPNEGO) SSO settings for LDAP.
//
// Required:
//   - Enabled, KeytabPath.
//
// Optional tuning:
//   - SPN: overrides the service principal name extracted from the keytab
//     (useful when Dex sits behind a reverse proxy that rewrites Host).
//   - KeytabPrincipal: selects a specific principal out of a multi-entry
//     keytab (e.g. "HTTP/dex.example.com").
//   - MaxClockSkew: seconds of acceptable clock skew between the KDC, the
//     client and Dex; defaults to gokrb5's 300s when unset.
//   - ExpectedRealm: rejects tickets from realms other than this one.
//   - UsernameFromPrincipal: "localpart" (default) or "userPrincipalName".
//   - FallbackToPassword: render the password form when SPNEGO is absent or
//     fails, instead of returning 401.
type kerberosConfig struct {
	Enabled               bool   `json:"enabled"`
	KeytabPath            string `json:"keytabPath"`
	SPN                   string `json:"spn"`
	KeytabPrincipal       string `json:"keytabPrincipal"`
	MaxClockSkew          int    `json:"maxClockSkew"`
	ExpectedRealm         string `json:"expectedRealm"`
	UsernameFromPrincipal string `json:"usernameFromPrincipal"`
	FallbackToPassword    bool   `json:"fallbackToPassword"`
}

func scopeString(i int) string {
	switch i {
	case ldap.ScopeBaseObject:
		return "base"
	case ldap.ScopeSingleLevel:
		return "one"
	case ldap.ScopeWholeSubtree:
		return "sub"
	default:
		return ""
	}
}

func parseScope(s string) (int, bool) {
	// NOTE(ericchiang): ScopeBaseObject doesn't really make sense for us because we
	// never know the user's or group's DN.
	switch s {
	case "", "sub":
		return ldap.ScopeWholeSubtree, true
	case "one":
		return ldap.ScopeSingleLevel, true
	}
	return 0, false
}

// Build a list of group attr name to user attr value matchers.
// Function exists here to allow backward compatibility between old and new
// group to user matching implementations.
// See "Config.GroupSearch.UserMatchers" comments for the details
func userMatchers(c *Config, logger *slog.Logger) []UserMatcher {
	if len(c.GroupSearch.UserMatchers) > 0 && c.GroupSearch.UserMatchers[0].UserAttr != "" {
		return c.GroupSearch.UserMatchers
	}

	if c.GroupSearch.UserAttr != "" || c.GroupSearch.GroupAttr != "" {
		logger.Warn(`use "groupSearch.userMatchers" option instead of "userAttr/groupAttr" fields`, "deprecated", true)
	}
	return []UserMatcher{
		{
			UserAttr:           c.GroupSearch.UserAttr,
			GroupAttr:          c.GroupSearch.GroupAttr,
			RecursionGroupAttr: c.GroupSearch.RecursionGroupAttr,
		},
	}
}

// Open returns an authentication strategy using LDAP.
func (c *Config) Open(id string, logger *slog.Logger) (connector.Connector, error) {
	logger = logger.With(slog.Group("connector", "type", "ldap", "id", id))
	conn, err := c.OpenConnector(logger)
	if err != nil {
		return nil, err
	}
	// If Kerberos is enabled, load the keytab and bind SPNEGO middleware.
	// The presence of a non-nil krb on ldapConnector is the single source of
	// truth for "SPNEGO is live"; TrySPNEGO short-circuits when it's nil.
	if lc, ok := conn.(*ldapConnector); ok && lc.krbConf.Enabled && lc.krb == nil {
		st, kerr := loadKerberosState(lc.krbConf)
		if kerr != nil {
			logger.Warn("failed to initialize kerberos; disabling kerberos", "err", kerr)
		} else {
			lc.krb = st
			logger.Info("kerberos SPNEGO enabled for LDAP connector",
				"keytab", lc.krbConf.KeytabPath,
				"spn", lc.krbConf.SPN,
				"keytab_principal", lc.krbConf.KeytabPrincipal,
				"expected_realm", lc.krbConf.ExpectedRealm,
				"fallback_to_password", lc.krbConf.FallbackToPassword,
			)
		}
	}
	return connector.Connector(conn), nil
}

type refreshData struct {
	Username string     `json:"username"`
	Entry    ldap.Entry `json:"entry"`
}

// OpenConnector is the same as Open but returns a type with all implemented connector interfaces.
func (c *Config) OpenConnector(logger *slog.Logger) (interface {
	connector.Connector
	connector.PasswordConnector
	connector.RefreshConnector
}, error,
) {
	return c.openConnector(logger)
}

func (c *Config) openConnector(logger *slog.Logger) (*ldapConnector, error) {
	requiredFields := []struct {
		name string
		val  string
	}{
		{"host", c.Host},
		{"userSearch.baseDN", c.UserSearch.BaseDN},
	}

	for _, field := range requiredFields {
		if field.val == "" {
			return nil, fmt.Errorf("ldap: missing required field %q", field.name)
		}
	}

	if len(c.UserSearch.Username) == 0 {
		return nil, fmt.Errorf("ldap: missing required field %q", "userSearch.username")
	}

	var (
		host string
		err  error
	)
	if host, _, err = net.SplitHostPort(c.Host); err != nil {
		host = c.Host
		if c.InsecureNoSSL {
			c.Host += ":389"
		} else {
			c.Host += ":636"
		}
	}

	tlsConfig := &tls.Config{ServerName: host, InsecureSkipVerify: c.InsecureSkipVerify}
	if c.RootCA != "" || len(c.RootCAData) != 0 {
		data := c.RootCAData
		if len(data) == 0 {
			var err error
			if data, err = os.ReadFile(c.RootCA); err != nil {
				return nil, fmt.Errorf("ldap: read ca file: %v", err)
			}
		}
		rootCAs := x509.NewCertPool()
		if !rootCAs.AppendCertsFromPEM(data) {
			return nil, fmt.Errorf("ldap: no certs found in ca file")
		}
		tlsConfig.RootCAs = rootCAs
	}

	if c.ClientKey != "" && c.ClientCert != "" {
		cert, err := tls.LoadX509KeyPair(c.ClientCert, c.ClientKey)
		if err != nil {
			return nil, fmt.Errorf("ldap: load client cert failed: %v", err)
		}
		tlsConfig.Certificates = append(tlsConfig.Certificates, cert)
	}
	userSearchScope, ok := parseScope(c.UserSearch.Scope)
	if !ok {
		return nil, fmt.Errorf("userSearch.Scope unknown value %q", c.UserSearch.Scope)
	}
	groupSearchScope, ok := parseScope(c.GroupSearch.Scope)
	if !ok {
		return nil, fmt.Errorf("groupSearch.Scope unknown value %q", c.GroupSearch.Scope)
	}

	// TODO(nabokihms): remove it after deleting deprecated groupSearch options
	c.GroupSearch.UserMatchers = userMatchers(c, logger)

	// Normalize Kerberos defaults. We persist krbConf only when it is
	// usable (Enabled + KeytabPath set); otherwise it stays at the zero
	// value and Open() will skip loadKerberosState — which keeps krb nil
	// and effectively disables SPNEGO without any extra flag.
	var krbConf kerberosConfig
	if c.Kerberos != nil && c.Kerberos.Enabled {
		krbConf = *c.Kerberos
		if krbConf.UsernameFromPrincipal == "" {
			krbConf.UsernameFromPrincipal = "localpart"
		}
		if krbConf.KeytabPath == "" {
			logger.Warn("kerberos enabled but keytabPath is empty; disabling kerberos")
			krbConf = kerberosConfig{}
		}
	}

	lc := &ldapConnector{
		Config:           *c,
		userSearchScope:  userSearchScope,
		groupSearchScope: groupSearchScope,
		tlsConfig:        tlsConfig,
		usernameAttrs:    c.UserSearch.Username,
		logger:           logger,
		krbConf:          krbConf,
	}
	return lc, nil
}

var (
	_ connector.PasswordConnector = (*ldapConnector)(nil)
	_ connector.RefreshConnector  = (*ldapConnector)(nil)
	_ connector.SPNEGOAware       = (*ldapConnector)(nil)
)

type ldapConnector struct {
	Config

	userSearchScope  int
	groupSearchScope int

	tlsConfig *tls.Config

	usernameAttrs []string

	logger *slog.Logger

	// Kerberos/SPNEGO support. krb is nil until the keytab has been loaded
	// successfully in Open(); TrySPNEGO uses (krb == nil) as the single
	// "is SPNEGO available" check, so no separate enable flag is needed.
	krbConf kerberosConfig
	krb     *krbState
	// krbLookupUserHook allows tests to replace the LDAP user lookup entirely.
	// When set it is authoritative: lookupKerberosUser does not fall through
	// to a real LDAP search. Tests signal "user not found" by returning an
	// error, not by returning a zero entry with a nil error.
	krbLookupUserHook func(ctx context.Context, c *ldapConnector, username string) (ldap.Entry, error)
}

// do initializes a connection to the LDAP directory and passes it to the
// provided function. It then performs appropriate teardown or reuse before
// returning.
func (c *ldapConnector) do(_ context.Context, f func(c *ldap.Conn) error) error {
	// TODO(ericchiang): support context here
	var (
		conn *ldap.Conn
		err  error
	)

	switch {
	case c.InsecureNoSSL:
		u := url.URL{Scheme: "ldap", Host: c.Host}
		conn, err = ldap.DialURL(u.String())
	case c.StartTLS:
		u := url.URL{Scheme: "ldap", Host: c.Host}
		conn, err = ldap.DialURL(u.String())
		if err != nil {
			return fmt.Errorf("failed to connect: %v", err)
		}
		if err := conn.StartTLS(c.tlsConfig); err != nil {
			return fmt.Errorf("start TLS failed: %v", err)
		}
	default:
		u := url.URL{Scheme: "ldaps", Host: c.Host}
		conn, err = ldap.DialURL(u.String(), ldap.DialWithTLSConfig(c.tlsConfig))
	}
	if err != nil {
		return fmt.Errorf("failed to connect: %v", err)
	}
	defer conn.Close()

	// If bindDN and bindPW are empty this will default to an anonymous bind.
	if c.BindDN == "" && c.BindPW == "" {
		if err := conn.UnauthenticatedBind(""); err != nil {
			return fmt.Errorf("ldap: initial anonymous bind failed: %v", err)
		}
	} else if err := conn.Bind(c.BindDN, c.BindPW); err != nil {
		return fmt.Errorf("ldap: initial bind for user %q failed: %v", c.BindDN, err)
	}

	return f(conn)
}

func (c *ldapConnector) getAttrs(e ldap.Entry, name string) []string {
	for _, a := range e.Attributes {
		if a.Name != name {
			continue
		}
		return a.Values
	}
	if strings.ToLower(name) == "dn" {
		return []string{e.DN}
	}

	c.logger.Debug("attribute is not fround in entry", "attribute", name)
	return nil
}

func (c *ldapConnector) getAttr(e ldap.Entry, name string) string {
	if a := c.getAttrs(e, name); len(a) > 0 {
		return a[0]
	}
	return ""
}

func (c *ldapConnector) identityFromEntry(user ldap.Entry) (ident connector.Identity, err error) {
	// If we're missing any attributes, such as email or ID, we want to report
	// an error rather than continuing.
	missing := []string{}

	// Fill the identity struct using the attributes from the user entry.
	if ident.UserID = c.getAttr(user, c.UserSearch.IDAttr); ident.UserID == "" {
		missing = append(missing, c.UserSearch.IDAttr)
	}

	if c.UserSearch.NameAttr != "" {
		if ident.Username = c.getAttr(user, c.UserSearch.NameAttr); ident.Username == "" {
			missing = append(missing, c.UserSearch.NameAttr)
		}
	}

	if c.UserSearch.PreferredUsernameAttrAttr != "" {
		if ident.PreferredUsername = c.getAttr(user, c.UserSearch.PreferredUsernameAttrAttr); ident.PreferredUsername == "" {
			missing = append(missing, c.UserSearch.PreferredUsernameAttrAttr)
		}
	}

	if c.UserSearch.EmailSuffix != "" {
		ident.Email = ident.Username + "@" + c.UserSearch.EmailSuffix
	} else if ident.Email = c.getAttr(user, c.UserSearch.EmailAttr); ident.Email == "" {
		missing = append(missing, c.UserSearch.EmailAttr)
	}
	// TODO(ericchiang): Let this value be set from an attribute.
	ident.EmailVerified = true

	if len(missing) != 0 {
		err := fmt.Errorf("ldap: entry %q missing following required attribute(s): %q", user.DN, missing)
		return connector.Identity{}, err
	}
	return ident, nil
}

func (c *ldapConnector) userEntry(conn *ldap.Conn, username string) (user ldap.Entry, found bool, err error) {
	var filter string
	escapedUsername := ldap.EscapeFilter(username)

	attrFilters := make([]string, 0, len(c.usernameAttrs))
	for _, attr := range c.usernameAttrs {
		attrFilters = append(attrFilters, fmt.Sprintf("(%s=%s)", attr, escapedUsername))
	}
	if len(attrFilters) == 1 {
		filter = attrFilters[0] // Skip OR wrapper for single attribute
	} else {
		filter = fmt.Sprintf("(|%s)", strings.Join(attrFilters, ""))
	}

	if c.UserSearch.Filter != "" {
		filter = fmt.Sprintf("(&%s%s)", c.UserSearch.Filter, filter)
	}

	// Initial search.
	req := &ldap.SearchRequest{
		BaseDN: c.UserSearch.BaseDN,
		Filter: filter,
		Scope:  c.userSearchScope,
		// We only need to search for these specific requests.
		Attributes: []string{
			c.UserSearch.IDAttr,
			c.UserSearch.EmailAttr,
			// TODO(ericchiang): what if this contains duplicate values?
		},
	}

	req.Attributes = append(req.Attributes, c.usernameAttrs...)

	for _, matcher := range c.GroupSearch.UserMatchers {
		req.Attributes = append(req.Attributes, matcher.UserAttr)
	}

	if c.UserSearch.NameAttr != "" {
		req.Attributes = append(req.Attributes, c.UserSearch.NameAttr)
	}

	if c.UserSearch.PreferredUsernameAttrAttr != "" {
		req.Attributes = append(req.Attributes, c.UserSearch.PreferredUsernameAttrAttr)
	}

	c.logger.Info("performing ldap search",
		"base_dn", req.BaseDN, "scope", scopeString(req.Scope), "filter", req.Filter)
	resp, err := conn.Search(req)
	if err != nil {
		return ldap.Entry{}, false, fmt.Errorf("ldap: search with filter %q failed: %v", req.Filter, err)
	}

	switch n := len(resp.Entries); n {
	case 0:
		c.logger.Error("no results returned for filter", "filter", filter)
		return ldap.Entry{}, false, nil
	case 1:
		user = *resp.Entries[0]
		c.logger.Info("username mapped to entry", "username", username, "user_dn", user.DN)
		return user, true, nil
	default:
		return ldap.Entry{}, false, fmt.Errorf("ldap: filter returned multiple (%d) results: %q", n, filter)
	}
}

func (c *ldapConnector) Login(ctx context.Context, s connector.Scopes, username, password string) (ident connector.Identity, validPass bool, err error) {
	// make this check to avoid unauthenticated bind to the LDAP server.

	if password == "" {
		return connector.Identity{}, false, nil
	}

	var (
		// We want to return a different error if the user's password is incorrect vs
		// if there was an error.
		incorrectPass = false
		user          ldap.Entry
	)

	username = ldap.EscapeFilter(username)

	err = c.do(ctx, func(conn *ldap.Conn) error {
		entry, found, err := c.userEntry(conn, username)
		if err != nil {
			return err
		}
		if !found {
			incorrectPass = true
			return nil
		}
		user = entry

		// Try to authenticate as the distinguished name.
		if err := conn.Bind(user.DN, password); err != nil {
			// Detect a bad password through the LDAP error code.
			if ldapErr, ok := err.(*ldap.Error); ok {
				switch ldapErr.ResultCode {
				case ldap.LDAPResultInvalidCredentials:
					c.logger.Error("invalid password for user", "user_dn", user.DN)
					incorrectPass = true
					return nil
				case ldap.LDAPResultConstraintViolation:
					c.logger.Error("constraint violation for user", "user_dn", user.DN, "err", ldapErr.Error())
					incorrectPass = true
					return nil
				}
			} // will also catch all ldap.Error without a case statement above
			return fmt.Errorf("ldap: failed to bind as dn %q: %v", user.DN, err)
		}
		return nil
	})
	if err != nil {
		return connector.Identity{}, false, err
	}
	if incorrectPass {
		return connector.Identity{}, false, nil
	}

	if ident, err = c.identityFromEntry(user); err != nil {
		return connector.Identity{}, false, err
	}

	if s.Groups {
		groups, err := c.groups(ctx, user)
		if err != nil {
			return connector.Identity{}, false, fmt.Errorf("ldap: failed to query groups: %v", err)
		}
		ident.Groups = groups
	}

	if s.OfflineAccess {
		refresh := refreshData{
			Username: username,
			Entry:    user,
		}
		// Encode entry for follow up requests such as the groups query and
		// refresh attempts.
		if ident.ConnectorData, err = json.Marshal(refresh); err != nil {
			return connector.Identity{}, false, fmt.Errorf("ldap: marshal entry: %v", err)
		}
	}

	return ident, true, nil
}

func (c *ldapConnector) Refresh(ctx context.Context, s connector.Scopes, ident connector.Identity) (connector.Identity, error) {
	var data refreshData
	if err := json.Unmarshal(ident.ConnectorData, &data); err != nil {
		return ident, fmt.Errorf("ldap: failed to unmarshal internal data: %v", err)
	}

	var user ldap.Entry
	err := c.do(ctx, func(conn *ldap.Conn) error {
		entry, found, err := c.userEntry(conn, data.Username)
		if err != nil {
			return err
		}
		if !found {
			return fmt.Errorf("ldap: user not found %q", data.Username)
		}
		user = entry
		return nil
	})
	if err != nil {
		return ident, err
	}
	if user.DN != data.Entry.DN {
		return ident, fmt.Errorf("ldap: refresh for username %q expected DN %q got %q", data.Username, data.Entry.DN, user.DN)
	}

	newIdent, err := c.identityFromEntry(user)
	if err != nil {
		return ident, err
	}
	newIdent.ConnectorData = ident.ConnectorData

	if s.Groups {
		groups, err := c.groups(ctx, user)
		if err != nil {
			return connector.Identity{}, fmt.Errorf("ldap: failed to query groups: %v", err)
		}
		newIdent.Groups = groups
	}
	return newIdent, nil
}

func (c *ldapConnector) groups(ctx context.Context, user ldap.Entry) ([]string, error) {
	if c.GroupSearch.BaseDN == "" {
		c.logger.Debug("No groups returned because no groups baseDN has been configured.", "base_dn", c.getAttr(user, c.UserSearch.NameAttr))
		return nil, nil
	}

	var groupNames []string

	for _, matcher := range c.GroupSearch.UserMatchers {
		// Initial Search
		var groups []*ldap.Entry
		for _, attr := range c.getAttrs(user, matcher.UserAttr) {
			obtained, filter, err := c.queryGroups(ctx, matcher.GroupAttr, attr)
			if err != nil {
				return nil, err
			}
			gotGroups := len(obtained) != 0
			if !gotGroups {
				// TODO(ericchiang): Is this going to spam the logs?
				c.logger.Error("ldap: groups search returned no groups", "filter", filter)
			}
			groups = append(groups, obtained...)
		}

		// If RecursionGroupAttr is not set, convert direct groups into names and return
		if matcher.RecursionGroupAttr == "" {
			for _, group := range groups {
				name := c.getAttr(*group, c.GroupSearch.NameAttr)
				if name == "" {
					return nil, fmt.Errorf(
						"ldap: group entity %q missing required attribute %q",
						group.DN, c.GroupSearch.NameAttr,
					)
				}
				groupNames = append(groupNames, name)
			}
			continue
		}

		// Recursive Search
		c.logger.Info("Recursive group search enabled", "groupAttr", matcher.GroupAttr, "recursionAttr", matcher.RecursionGroupAttr)
		for {
			var nextLevel []*ldap.Entry
			for _, group := range groups {
				name := c.getAttr(*group, c.GroupSearch.NameAttr)
				if name == "" {
					return nil, fmt.Errorf("ldap: group entity %q missing required attribute %q",
						group.DN, c.GroupSearch.NameAttr)
				}

				// Prevent duplicates and circular references.
				duplicate := false
				for _, existingName := range groupNames {
					if name == existingName {
						c.logger.Debug("Found duplicate group", "name", name)
						duplicate = true
						break
					}
				}
				if duplicate {
					continue
				}

				groupNames = append(groupNames, name)

				// Search for parent groups using the group's DN.
				parents, filter, err := c.queryGroups(ctx, matcher.RecursionGroupAttr, group.DN)
				if err != nil {
					return nil, err
				}
				if len(parents) == 0 {
					c.logger.Debug("No parent groups found", "filter", filter)
				} else {
					nextLevel = append(nextLevel, parents...)
				}
			}
			if len(nextLevel) == 0 {
				break
			}
			groups = nextLevel
		}
	}
	return groupNames, nil
}

func (c *ldapConnector) queryGroups(ctx context.Context, memberAttr, dn string) ([]*ldap.Entry, string, error) {
	filter := fmt.Sprintf("(%s=%s)", memberAttr, ldap.EscapeFilter(dn))
	if c.GroupSearch.Filter != "" {
		filter = fmt.Sprintf("(&%s%s)", c.GroupSearch.Filter, filter)
	}

	req := &ldap.SearchRequest{
		BaseDN:     c.GroupSearch.BaseDN,
		Filter:     filter,
		Scope:      c.groupSearchScope,
		Attributes: []string{c.GroupSearch.NameAttr},
	}

	var entries []*ldap.Entry
	if err := c.do(ctx, func(conn *ldap.Conn) error {
		c.logger.Info(
			"performing ldap search",
			"base_dn", req.BaseDN,
			"scope", scopeString(req.Scope),
			"filter", req.Filter,
		)
		resp, err := conn.Search(req)
		if err != nil {
			if ldapErr, ok := err.(*ldap.Error); ok && ldapErr.ResultCode == ldap.LDAPResultNoSuchObject {
				c.logger.Info("LDAP search returned no groups", "filter", filter)
				return nil
			}
			return fmt.Errorf("ldap: search failed: %v", err)
		}
		entries = append(entries, resp.Entries...)
		return nil
	}); err != nil {
		return nil, filter, err
	}
	return entries, filter, nil
}

func (c *ldapConnector) Prompt() string {
	return c.UsernamePrompt
}
