{
 "kind": "discovery#restDescription",
 "etag": "\"l66ggWbucbkBw9Lpos72oziyefE/pVfb1ajMeYIw5IrU4jq20F5dMAg\"",
 "discoveryVersion": "v1",
 "id": "tagmanager:v1",
 "name": "tagmanager",
 "canonicalName": "Tag Manager",
 "version": "v1",
 "revision": "20141024",
 "title": "Tag Manager API",
 "description": "API for accessing Tag Manager accounts and containers.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/tag-manager/api/v1/",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/tagmanager/v1/",
 "basePath": "/tagmanager/v1/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "tagmanager/v1/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/tagmanager.delete.containers": {
     "description": "Delete your Google Tag Manager containers"
    },
    "https://www.googleapis.com/auth/tagmanager.edit.containers": {
     "description": "Manage your Google Tag Manager containers"
    },
    "https://www.googleapis.com/auth/tagmanager.edit.containerversions": {
     "description": "Manage your Google Tag Manager container versions"
    },
    "https://www.googleapis.com/auth/tagmanager.manage.accounts": {
     "description": "Manage your Google Tag Manager accounts"
    },
    "https://www.googleapis.com/auth/tagmanager.manage.users": {
     "description": "Manage user permissions of your Google Tag Manager data"
    },
    "https://www.googleapis.com/auth/tagmanager.publish": {
     "description": "Publish your Google Tag Manager containers"
    },
    "https://www.googleapis.com/auth/tagmanager.readonly": {
     "description": "View your Google Tag Manager containers"
    }
   }
  }
 },
 "resources": {
  "accounts": {
   "methods": {
    "get": {
     "id": "tagmanager.accounts.get",
     "path": "accounts/{accountId}",
     "httpMethod": "GET",
     "description": "Gets a GTM Account.",
     "scopes": [
      "https://www.googleapis.com/auth/tagmanager.edit.containers",
      "https://www.googleapis.com/auth/tagmanager.manage.accounts",
      "https://www.googleapis.com/auth/tagmanager.readonly"
     ]
    },
    "list": {
     "id": "tagmanager.accounts.list",
     "path": "accounts",
     "httpMethod": "GET",
     "description": "Lists all GTM Accounts that a user has access to.",
     "scopes": [
      "https://www.googleapis.com/auth/tagmanager.edit.containers",
      "https://www.googleapis.com/auth/tagmanager.manage.accounts",
      "https://www.googleapis.com/auth/tagmanager.readonly"
     ]
    },
    "update": {
     "id": "tagmanager.accounts.update",
     "path": "accounts/{accountId}",
     "httpMethod": "PUT",
     "description": "Updates a GTM Account.",
     "scopes": [
      "https://www.googleapis.com/auth/tagmanager.manage.accounts"
     ]
    }
   },
   "resources": {
    "containers": {
     "methods": {
      "create": {
       "id": "tagmanager.accounts.containers.create",
       "path": "accounts/{accountId}/containers",
       "httpMethod": "POST",
       "description": "Creates a Container.",
       "scopes": [
        "https://www.googleapis.com/auth/tagmanager.edit.containers"
       ]
      },
      "delete": {
       "id": "tagmanager.accounts.containers.delete",
       "path": "accounts/{accountId}/containers/{containerId}",
       "httpMethod": "DELETE",
       "description": "Deletes a Container.",
       "scopes": [
        "https://www.googleapis.com/auth/tagmanager.delete.containers"
       ]
      },
      "get": {
       "id": "tagmanager.accounts.containers.get",
       "path": "accounts/{accountId}/containers/{containerId}",
       "httpMethod": "GET",
       "description": "Gets a Container.",
       "scopes": [
        "https://www.googleapis.com/auth/tagmanager.edit.containers",
        "https://www.googleapis.com/auth/tagmanager.readonly"
       ]
      },
      "list": {
       "id": "tagmanager.accounts.containers.list",
       "path": "accounts/{accountId}/containers",
       "httpMethod": "GET",
       "description": "Lists all Containers that belongs to a GTM Account.",
       "scopes": [
        "https://www.googleapis.com/auth/tagmanager.edit.containers",
        "https://www.googleapis.com/auth/tagmanager.readonly"
       ]
      },
      "update": {
       "id": "tagmanager.accounts.containers.update",
       "path": "accounts/{accountId}/containers/{containerId}",
       "httpMethod": "PUT",
       "description": "Updates a Container.",
       "scopes": [
        "https://www.googleapis.com/auth/tagmanager.edit.containers"
       ]
      }
     },
     "resources": {
      "macros": {
       "methods": {
        "create": {
         "id": "tagmanager.accounts.containers.macros.create",
         "path": "accounts/{accountId}/containers/{containerId}/macros",
         "httpMethod": "POST",
         "description": "Creates a GTM Macro.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ]
        },
        "delete": {
         "id": "tagmanager.accounts.containers.macros.delete",
         "path": "accounts/{accountId}/containers/{containerId}/macros/{macroId}",
         "httpMethod": "DELETE",
         "description": "Deletes a GTM Macro.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ]
        },
        "get": {
         "id": "tagmanager.accounts.containers.macros.get",
         "path": "accounts/{accountId}/containers/{containerId}/macros/{macroId}",
         "httpMethod": "GET",
         "description": "Gets a GTM Macro.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ]
        },
        "list": {
         "id": "tagmanager.accounts.containers.macros.list",
         "path": "accounts/{accountId}/containers/{containerId}/macros",
         "httpMethod": "GET",
         "description": "Lists all GTM Macros of a Container.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ]
        },
        "update": {
         "id": "tagmanager.accounts.containers.macros.update",
         "path": "accounts/{accountId}/containers/{containerId}/macros/{macroId}",
         "httpMethod": "PUT",
         "description": "Updates a GTM Macro.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ]
        }
       }
      },
      "rules": {
       "methods": {
        "create": {
         "id": "tagmanager.accounts.containers.rules.create",
         "path": "accounts/{accountId}/containers/{containerId}/rules",
         "httpMethod": "POST",
         "description": "Creates a GTM Rule.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ]
        },
        "delete": {
         "id": "tagmanager.accounts.containers.rules.delete",
         "path": "accounts/{accountId}/containers/{containerId}/rules/{ruleId}",
         "httpMethod": "DELETE",
         "description": "Deletes a GTM Rule.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ]
        },
        "get": {
         "id": "tagmanager.accounts.containers.rules.get",
         "path": "accounts/{accountId}/containers/{containerId}/rules/{ruleId}",
         "httpMethod": "GET",
         "description": "Gets a GTM Rule.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ]
        },
        "list": {
         "id": "tagmanager.accounts.containers.rules.list",
         "path": "accounts/{accountId}/containers/{containerId}/rules",
         "httpMethod": "GET",
         "description": "Lists all GTM Rules of a Container.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ]
        },
        "update": {
         "id": "tagmanager.accounts.containers.rules.update",
         "path": "accounts/{accountId}/containers/{containerId}/rules/{ruleId}",
         "httpMethod": "PUT",
         "description": "Updates a GTM Rule.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ]
        }
       }
      },
      "tags": {
       "methods": {
        "create": {
         "id": "tagmanager.accounts.containers.tags.create",
         "path": "accounts/{accountId}/containers/{containerId}/tags",
         "httpMethod": "POST",
         "description": "Creates a GTM Tag.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ]
        },
        "delete": {
         "id": "tagmanager.accounts.containers.tags.delete",
         "path": "accounts/{accountId}/containers/{containerId}/tags/{tagId}",
         "httpMethod": "DELETE",
         "description": "Deletes a GTM Tag.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ]
        },
        "get": {
         "id": "tagmanager.accounts.containers.tags.get",
         "path": "accounts/{accountId}/containers/{containerId}/tags/{tagId}",
         "httpMethod": "GET",
         "description": "Gets a GTM Tag.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ]
        },
        "list": {
         "id": "tagmanager.accounts.containers.tags.list",
         "path": "accounts/{accountId}/containers/{containerId}/tags",
         "httpMethod": "GET",
         "description": "Lists all GTM Tags of a Container.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ]
        },
        "update": {
         "id": "tagmanager.accounts.containers.tags.update",
         "path": "accounts/{accountId}/containers/{containerId}/tags/{tagId}",
         "httpMethod": "PUT",
         "description": "Updates a GTM Tag.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ]
        }
       }
      },
      "triggers": {
       "methods": {
        "create": {
         "id": "tagmanager.accounts.containers.triggers.create",
         "path": "accounts/{accountId}/containers/{containerId}/triggers",
         "httpMethod": "POST",
         "description": "Creates a GTM Trigger.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ]
        },
        "delete": {
         "id": "tagmanager.accounts.containers.triggers.delete",
         "path": "accounts/{accountId}/containers/{containerId}/triggers/{triggerId}",
         "httpMethod": "DELETE",
         "description": "Deletes a GTM Trigger.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ]
        },
        "get": {
         "id": "tagmanager.accounts.containers.triggers.get",
         "path": "accounts/{accountId}/containers/{containerId}/triggers/{triggerId}",
         "httpMethod": "GET",
         "description": "Gets a GTM Trigger.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ]
        },
        "list": {
         "id": "tagmanager.accounts.containers.triggers.list",
         "path": "accounts/{accountId}/containers/{containerId}/triggers",
         "httpMethod": "GET",
         "description": "Lists all GTM Triggers of a Container.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ]
        },
        "update": {
         "id": "tagmanager.accounts.containers.triggers.update",
         "path": "accounts/{accountId}/containers/{containerId}/triggers/{triggerId}",
         "httpMethod": "PUT",
         "description": "Updates a GTM Trigger.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ]
        }
       }
      },
      "variables": {
       "methods": {
        "create": {
         "id": "tagmanager.accounts.containers.variables.create",
         "path": "accounts/{accountId}/containers/{containerId}/variables",
         "httpMethod": "POST",
         "description": "Creates a GTM Variable.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ]
        },
        "delete": {
         "id": "tagmanager.accounts.containers.variables.delete",
         "path": "accounts/{accountId}/containers/{containerId}/variables/{variableId}",
         "httpMethod": "DELETE",
         "description": "Deletes a GTM Variable.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ]
        },
        "get": {
         "id": "tagmanager.accounts.containers.variables.get",
         "path": "accounts/{accountId}/containers/{containerId}/variables/{variableId}",
         "httpMethod": "GET",
         "description": "Gets a GTM Variable.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ]
        },
        "list": {
         "id": "tagmanager.accounts.containers.variables.list",
         "path": "accounts/{accountId}/containers/{containerId}/variables",
         "httpMethod": "GET",
         "description": "Lists all GTM Variables of a Container.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ]
        },
        "update": {
         "id": "tagmanager.accounts.containers.variables.update",
         "path": "accounts/{accountId}/containers/{containerId}/variables/{variableId}",
         "httpMethod": "PUT",
         "description": "Updates a GTM Variable.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ]
        }
       }
      },
      "versions": {
       "methods": {
        "create": {
         "id": "tagmanager.accounts.containers.versions.create",
         "path": "accounts/{accountId}/containers/{containerId}/versions",
         "httpMethod": "POST",
         "description": "Creates a Container Version.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
         ]
        },
        "delete": {
         "id": "tagmanager.accounts.containers.versions.delete",
         "path": "accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}",
         "httpMethod": "DELETE",
         "description": "Deletes a Container Version.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
         ]
        },
        "get": {
         "id": "tagmanager.accounts.containers.versions.get",
         "path": "accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}",
         "httpMethod": "GET",
         "description": "Gets a Container Version.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.edit.containerversions",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ]
        },
        "list": {
         "id": "tagmanager.accounts.containers.versions.list",
         "path": "accounts/{accountId}/containers/{containerId}/versions",
         "httpMethod": "GET",
         "description": "Lists all Container Versions of a GTM Container.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.edit.containerversions",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ]
        },
        "publish": {
         "id": "tagmanager.accounts.containers.versions.publish",
         "path": "accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/publish",
         "httpMethod": "POST",
         "description": "Publishes a Container Version.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.publish"
         ]
        },
        "restore": {
         "id": "tagmanager.accounts.containers.versions.restore",
         "path": "accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/restore",
         "httpMethod": "POST",
         "description": "Restores a Container Version. This will overwrite the container's current configuration (including its macros, rules and tags). The operation will not have any effect on the version that is being served (i.e. the published version).",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ]
        },
        "undelete": {
         "id": "tagmanager.accounts.containers.versions.undelete",
         "path": "accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/undelete",
         "httpMethod": "POST",
         "description": "Undeletes a Container Version.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
         ]
        },
        "update": {
         "id": "tagmanager.accounts.containers.versions.update",
         "path": "accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}",
         "httpMethod": "PUT",
         "description": "Updates a Container Version.",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
         ]
        }
       }
      }
     }
    },
    "permissions": {
     "methods": {
      "create": {
       "id": "tagmanager.accounts.permissions.create",
       "path": "accounts/{accountId}/permissions",
       "httpMethod": "POST",
       "description": "Creates a user's Account & Container Permissions.",
       "scopes": [
        "https://www.googleapis.com/auth/tagmanager.manage.users"
       ]
      },
      "delete": {
       "id": "tagmanager.accounts.permissions.delete",
       "path": "accounts/{accountId}/permissions/{permissionId}",
       "httpMethod": "DELETE",
       "description": "Removes a user from the account, revoking access to it and all of its containers.",
       "scopes": [
        "https://www.googleapis.com/auth/tagmanager.manage.users"
       ]
      },
      "get": {
       "id": "tagmanager.accounts.permissions.get",
       "path": "accounts/{accountId}/permissions/{permissionId}",
       "httpMethod": "GET",
       "description": "Gets a user's Account & Container Permissions.",
       "scopes": [
        "https://www.googleapis.com/auth/tagmanager.manage.users"
       ]
      },
      "list": {
       "id": "tagmanager.accounts.permissions.list",
       "path": "accounts/{accountId}/permissions",
       "httpMethod": "GET",
       "description": "List all users that have access to the account along with Account and Container Permissions granted to each of them.",
       "scopes": [
        "https://www.googleapis.com/auth/tagmanager.manage.users"
       ]
      },
      "update": {
       "id": "tagmanager.accounts.permissions.update",
       "path": "accounts/{accountId}/permissions/{permissionId}",
       "httpMethod": "PUT",
       "description": "Updates a user's Account & Container Permissions.",
       "scopes": [
        "https://www.googleapis.com/auth/tagmanager.manage.users"
       ]
      }
     }
    }
   }
  }
 }
}
