//go:build ignore
// +build ignore

// This file is used to generate static JWKs for tests.

package main

import (
	"bytes"
	"crypto"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"encoding/hex"
	"encoding/json"
	"go/format"
	"io"
	"log"
	"os"
	"text/template"

	"github.com/go-jose/go-jose/v4"
)

func newUUID() string {
	u := make([]byte, 16)
	if _, err := io.ReadFull(rand.Reader, u); err != nil {
		panic(err)
	}

	u[8] = (u[8] | 0x80) & 0xBF
	u[6] = (u[6] | 0x40) & 0x4F

	return hex.EncodeToString(u)
}

var tmpl = template.Must(template.New("jwks.go").Parse(`
// This file was generated by gen_jwks.go

package conformance

import jose "github.com/go-jose/go-jose/v4"

type keyPair struct {
	Public  *jose.JSONWebKey
	Private *jose.JSONWebKey
}

// keys are generated beforehand so tests don't spend time on crypto key generation.
var jsonWebKeys = []keyPair{
{{- range $i, $pair := .Keys }}
	{
		Public:  mustLoadJWK({{ $pair.Public }}),
		Private: mustLoadJWK({{ $pair.Private }}),
	},
{{- end }}
}
`[1:])) // Remove the first newline.

type keyPair struct {
	Public  string
	Private string
}

type keySpec struct {
	count     int
	algorithm string
	generate  func() (crypto.Signer, error)
}

func newKeyPair(algorithm string, key crypto.Signer) keyPair {
	priv := jose.JSONWebKey{
		Key:       key,
		KeyID:     newUUID(),
		Algorithm: algorithm,
		Use:       "sig",
	}
	pub := jose.JSONWebKey{
		Key:       key.Public(),
		KeyID:     newUUID(),
		Algorithm: algorithm,
		Use:       "sig",
	}

	privBytes, err := json.MarshalIndent(priv, "\t\t", "\t")
	if err != nil {
		log.Fatalf("marshal priv: %v", err)
	}
	pubBytes, err := json.MarshalIndent(pub, "\t\t", "\t")
	if err != nil {
		log.Fatalf("marshal pub: %v", err)
	}

	return keyPair{
		Private: "`" + string(privBytes) + "`",
		Public:  "`" + string(pubBytes) + "`",
	}
}

func main() {
	var tmplData struct {
		Keys []keyPair
	}

	specs := []keySpec{
		{
			count:     5,
			algorithm: "RS256",
			generate: func() (crypto.Signer, error) {
				return rsa.GenerateKey(rand.Reader, 2048)
			},
		},
		{
			count:     2,
			algorithm: "ES256",
			generate: func() (crypto.Signer, error) {
				return ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
			},
		},
	}

	for _, spec := range specs {
		for i := 0; i < spec.count; i++ {
			key, err := spec.generate()
			if err != nil {
				log.Fatalf("gen %s key: %v", spec.algorithm, err)
			}
			tmplData.Keys = append(tmplData.Keys, newKeyPair(spec.algorithm, key))
		}
	}

	buff := new(bytes.Buffer)
	if err := tmpl.Execute(buff, tmplData); err != nil {
		log.Fatalf("execute tmpl: %v", err)
	}

	out, err := format.Source(buff.Bytes())
	if err != nil {
		log.Fatalf("gofmt failed: %v", err)
	}
	if err := os.WriteFile("jwks.go", out, 0o644); err != nil {
		log.Fatal(err)
	}
}
