#!/bin/bash -e

mkdir -p _output/bin

sudo docker run \
    --cidfile=cid \
    -v $PWD:/go/src/github.com/coreos/dex:ro \
    -w /go/src/github.com/coreos/dex \
    golang:1.8.0-alpine \
    /bin/sh -x -c \
    'apk add --no-cache --update alpine-sdk && make release-binary'

sudo docker cp $( cat cid ):/go/bin/dex _output/bin/dex
sudo docker rm $( cat cid )
sudo rm cid
