#!/bin/bash

set -e

if [ -z $DEX_NAMESPACE ];then
        echo "Must export \$DEX_NAMESPACE"
        exit
fi

for RESOURCE in authcodes authrequests connectors oauth2clients offlinesessionses refreshtokens passwords signingkeies; do
        kubectl get --namespace=$DEX_NAMESPACE $RESOURCE.oidc.coreos.com  -o yaml
done

