#!/bin/bash

mkdir -p _output/bin

sudo rkt run \
    --volume dex,kind=host,source=$PWD \
    --mount volume=dex,target=/go/src/github.com/coreos/dex \
    --dns=8.8.8.8 \
    --net=host \
    --insecure-options=image \
    docker://golang:1.7.4-alpine \
    --exec=/bin/sh -- -x -c \
    'apk add --no-cache --update alpine-sdk && cd /go/src/github.com/coreos/dex && make release-binary'
