#!/bin/bash

mkdir -p _output/bin

sudo rkt run \
    --volume dex,kind=host,source=$PWD \
    --mount volume=dex,target=/go/src/github.com/coreos/dex \
    --dns=8.8.8.8 \
    --net=host \
    --insecure-options=image \
    docker://golang:1.7.1-alpine \
    --exec=/bin/sh -- -x -c \
	'apk add --no-cache --update alpine-sdk && go install -v github.com/coreos/dex/cmd/dex && cp /go/bin/dex /go/src/github.com/coreos/dex/_output/bin'
