name: PR Checks

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

permissions:
  contents: read

jobs:
  release-label:
    name: Release note label
    runs-on: ubuntu-latest

    if: github.repository == 'dexidp/dex'

    steps:
      - name: Check minimum labels
        uses: mheap/github-action-required-labels@8afbe8ae6ab7647d0c9f0cfa7c2f939650d22509 # v5.5
        with:
          mode: minimum
          count: 1
          labels: "release-note/ignore, kind/feature, release-note/new-feature, kind/enhancement, release-note/enhancement, kind/bug, release-note/bug-fix, release-note/breaking-change, release-note/deprecation, area/dependencies, release-note/dependency-update"
